const String ngrok ="https://ab5e12859e5d.ngrok-free.app";
const List<String> categories = [
  "Trousers",
  "Dress",
  "Sweater",
  "T-shirt",
  "Top",
  "Blouse",
  "Jacket",
  "Shorts",
  "Shirt",
  "Vest top",
  "Underwear bottom",
  "Skirt",
  "Hoodie",
  "Bra",
  "Socks",
  "Leggings/Tights",
  "Sneakers",
  "Cardigan",
  "Hat/beanie",
  "Garment Set",
  "Swimwear bottom",
  "Bag",
  "Earring",
  "Jumpsuit/Playsuit",
  "Pyjama set",
  "Blazer",
  "Other accessories",
  "Boots",
  "Scarf",
  "Bodysuit",
  "Hair/alice band",
  "Bikini top",
  "Sandals",
  "Swimsuit",
  "Sunglasses",
  "Necklace",
  "Cap/peaked",
  "Underwear Tights",
  "Coat",
  "Belt",
  "Polo shirt",
  "Hat/brim",
  "Other shoe",
  "Pyjama jumpsuit/playsuit",
  "Ballerinas",
  "Gloves",
  "Dungarees",
  "Slippers",
  "Hair clip",
  "Ring",
  "Hair string",
  "Pyjama bottom",
  "Heeled sandals",
  "Swimwear set",
  "Pumps",
  "Bracelet",
  "Underwear body",
  "Night gown",
  "Flat shoe",
  "Outdoor Waistcoat",
  "Tie",
  "Robe",
  "Outdoor trousers",
  "Flip flop",
  "Unknown",
  "Wedge",
  "Kids Underwear top",
  "Costumes",
  "Wallet",
  "Watch",
  "Tailored Waistcoat",
  "Sarong",
  "Outdoor overall",
  "Beanie",
  "Swimwear top",
  "Sleeping sack",
  "Underwear set",
  "Fine cosmetics",
  "Soft Toys",
  "Bootie",
  "Long John",
  "Umbrella",
  "Hair ties",
  "Waterbottle",
  "Heels",
  "Dog Wear",
  "Underdress",
  "Nipple covers",
  "Giftbox",
  "Side table",
  "Cap",
  "Earrings",
  "Felt hat",
  "Flat shoes",
  "Weekend/Gym bag",
  "Leg warmers",
  "Dog wear",
  "Bucket hat",
  "Underwear corset",
  "Accessories set",
  "Alice band",
  "Straw hat",
  "Backpack",
  "Sleep Bag",
  "Cross-body bag",
  "Marker pen",
  "Moccasins",
  "Mobile case",
  "Baby Bib",
  "Braces",
  "Chem. cosmetics",
  "Zipper head",
  "Shoulder bag",
  "Eyeglasses",
  "Wireless earphone case",
  "Tote bag",
  "Hairband",
  "Stain remover spray",
  "Toy",
  "Bumbag",
  "Pre-walkers",
  "Bra extender",
  "Wood balls",
  "Towel",
  "Sewing kit",
  "Washing bag",
  "Keychain",
  "Headband",
  "Cushion",
  "Blanket",
  "Clothing mist",
];

const List<String> genders = [
  'Ladieswear',
  'Baby/Children',
  'Divided',
  'Menswear',
  'Sport',
];

 const List<String> departments = [
    "Jersey",
    "Knitwear",
    "Trouser",
    "Blouse",
    "Dress",
    "Swimwear",
    "Kids Girl Jersey Fancy",
    "Expressive Lingerie",
    "Young Girl Jersey Fancy",
    "Jersey Fancy",
    "Jersey Basic",
    "Kids Boy Jersey Fancy",
    "Tops Fancy Jersey",
    "Jersey fancy",
    "Dresses",
    "Basic 1",
    "Jewellery",
    "Shirt",
    "Baby basics",
    "Tops Knitwear",
    "Young Boy Jersey Fancy",
    "Kids Girl Jersey Basic",
    "Baby Toys/Acc",
    "Outwear",
    "Tops Woven",
    "Ladies Sport Bras",
    "Baby Exclusive",
    "Blouse & Dress",
    "Kids Girl Dresses",
    "Small Accessories",
    "Baby Boy Jersey Fancy",
    "Casual Lingerie",
    "Baby Girl Jersey Fancy",
    "Newborn",
    "Shorts",
    "Bags",
    "Young Girl Jersey Basic",
    "Trousers",
    "Skirt",
    "Hair Accessories",
    "Accessories",
    "Woven bottoms",
    "Nightwear",
    "Woven top",
    "Jewellery Extended",
    "Kids Boy Jersey Basic",
    "Outdoor/Blazers",
    "Young Girl Dresses",
    "Kids Girl Knitwear",
    "Girls Small Acc/Bags",
    "Kids Girl Shoes",
    "Divided+",
    "Projects Dresses",
    "Woven Tops",
    "Kids Girl UW/NW",
    "Flats",
    "Light Basic Jersey",
    "Baby Girl Woven",
    "Young Girl Knitwear",
    "Knit & Woven",
    "Denim Trousers",
    "Take Care External",
    "Baby Boy Woven",
    "Young Girl UW/NW",
    "Skirts",
    "Ladies Sport Bottoms",
    "Baby Socks",
    "Young Boy Jersey Basic",
    "Baby Shoes",
    "Kids Boy Trouser",
    "Kids Boy Shoes",
    "Shoes",
    "Kids Girl Outdoor",
    "Premium Quality",
    "Kids Girl Trouser",
    "Young Girl Denim",
    "Baby Nightwear",
    "Equatorial Assortment",
    "Kids Girl Denim",
    "Young Girl Trouser",
    "Kids Girl Big Acc",
    "Kids Boy Denim",
    "Denim trousers",
    "Kids Boy Big Acc",
    "Kids Boy Outdoor",
    "Kids Boy Shirt",
    "Heels",
    "Projects Jersey & Knitwear",
    "Jersey/Knitwear Premium",
    "Belts",
    "Kids Girl S&T",
    "Woven Premium",
    "Woven Occasion",
    "Denim Other Garments",
    "Boots",
    "Trousers & Skirt",
    "Kids Boy UW/NW",
    "Young Boy Denim",
    "Scarves",
    "Gloves/Hats",
    "Young Girl Outdoor",
    "Other items",
    "Loungewear",
    "Studio Collection",
    "Kids Boy Knitwear",
    "Sneakers",
    "Men Sport Woven",
    "Functional Lingerie",
    "Suit",
    "UW",
    "Underwear Jersey",
    "Young Boy UW/NW",
    "Young Boy Shirt",
    "Young Girl Shoes",
    "Projects Woven Tops",
    "Basics",
    "Other Accessories",
    "Young Boy Outdoor",
    "Tops Girls",
    "Divided Shoes",
    "Projects Woven Bottoms",
    "Dresses DS",
    "Young Boy Trouser",
    "Sunglasses",
    "Bottoms Girls",
    "Jersey Fancy DS",
    "Kids Dress-up/Football",
    "Young Boy Shoes",
    "Baby Girl Knitwear",
    "Men Sport Tops",
    "Ladies Sport Acc",
    "Clean Lingerie",
    "Suit jacket",
    "Jacket Smart",
    "Kids Boy Shorts",
    "Jersey inactive from s1",
    "Tights basic",
    "Knitwear Basic",
    "Campaigns",
    "Mama Lingerie",
    "Socks",
    "Projects",
    "Shopbasket Socks",
    "Heavy Basic Jersey",
    "Baby Boy Outdoor",
    "Shoes / Boots inactive from s5",
    "Young Girl Big Acc",
    "Jacket Casual",
    "Men Sport Bottoms",
    "Kids Girl Swimwear",
    "Young Boy Big Acc",
    "Conscious Exclusive",
    "Socks Wall",
    "Socks Bin",
    "Shorts & Skirts",
    "Young Girl Swimwear",
    "Young Girl S&T",
    "Ladies Sport Woven",
    "Young Boy Shorts",
    "Young Boy Knitwear",
    "OL Extended Sizes",
    "Kids Boy Socks",
    "Tops Knitwear DS",
    "Bags & Items",
    "Kids Boy Swimwear",
    "Jersey Occasion",
    "Blazer S&T",
    "Shirt S&T",
    "Baby Boy Knitwear",
    "Nursing",
    "Blazer",
    "Woven",
    "Limited Edition",
    "Jacket Street",
    "Small Bags",
    "EQ H&M Man",
    "Men Sport Acc",
    "Baby Girl Outdoor",
    "Denim shorts",
    "Trouser S&T",
    "Promotion/ Other /Offer",
    "Young boy Swimwear",
    "Underwear Woven",
    "Boys Local Relevance",
    "Outdoor/Blazers DS",
    "Asia Assortment",
    "Read & React",
    "AK Bottoms",
    "Young Boy Socks",
    "Dress-up Boys",
    "Jersey License",
    "AK Dresses & Outdoor",
    "Outwear & Blazers",
    "Local relevance",
    "Trousers DS",
    "Everyday Waredrobe Denim",
    "Small Accessories Extended",
    "Divided Swimwear",
    "Girls Local Relevance",
    "Jacket",
    "Denim wardrobe H&M man inactive from S.6",
    "Kids Girl Exclusive",
    "Woven inactive from s1",
    "Kids Boy Exclusive",
    "Take care",
    "Shopbasket Lingerie",
    "Boys Small Acc & Bags",
    "Tops woven DS",
    "Knitwear inactive from s1",
    "Promotion / Other / Offer",
    "Tops Boys",
    "Equatorial",
    "AK Tops Jersey & Woven",
    "Sneakers small girl inactive from s2",
    "Skirts DS",
    "EQ & Special Collections",
    "Small Acc. Jewellery & Other",
    "Outdoor inactive from s1",
    "Special Collection",
    "AK Other",
    "AK Tops Knitwear",
    "On Demand",
    "Bottoms Boys",
    "Bottoms",
    "Price Items",
    "Divided+ inactive from s.1",
    "Sneakers big girl inactive from s2",
    "Promotion/Other/Offer",
    "License",
    "Blanks",
    "Shorts DS",
    "Jackets",
    "EQ Divided Basics",
    "Tops & Bottoms Other",
    "Accessories Boys",
    "Underwear Jersey Fancy inactive from s1",
    "Girls Projects",
    "Baby Girl Local Relevance",
    "EQ Ladies Denim",
    "Suit Extended inactive from s1",
    "Baby Boy Local Relevance",
    "Kids Girl License",
    "Test Ladies",
    "Shoes Other",
    "Shirt Extended inactive from s1",
    "Woven bottoms inactive from S.7",
    "Jersey inactive from S.6",
    "EQ Divided Blue",
    "Accessories Other",
    "Kids Boy License",
  ];

  const List<String> appearances = [
  'Solid',
  'All over pattern',
  'Melange',
  'Stripe',
  'Denim',
  'Front print',
  'Placement print',
  'Check',
  'Colour blocking',
  'Lace',
  'Other structure',
  'Application/3D',
  'Embroidery',
  'Mixed solid/pattern',
  'Glittering/Metallic',
  'Jacquard',
  'Sequin',
  'Dot',
  'Treatment',
  'Other pattern',
  'Contrast',
  'Metallic',
  'Chambray',
  'Slub',
  'Transparent',
  'Mesh',
  'Neps',
  'Unknown',
  'Argyle',
  'Hologram',
];
