import 'package:dashboard/features/Product/Manage%20Existing%20Product/All%20Product/Model/all_product.dart';

class SampleProducts {
  static const List<String> categories = [
    'All Products',
    'Women',
    'Men',
    'Accessories',
    'Electronics',
    'Home & Garden',
  ];

  static final List<Product> products = [
    Product(
      id: '1',
      name: 'Summer Dress',
      imageUrl: 'assets/images/main_image.jpg',
      price: 49.99,
      rating: 4.5,
      status: 'trend',
      category: 'Women',
      amount: 25,
    ),
    Product(
      id: '2',
      name: 'Casual Shirt',
      imageUrl: 'assets/images/main_image.jpg',
      price: 29.99,
      rating: 4.2,
      status: 'sale',
      category: 'Men',
      amount: 42,
    ),
    Product(
      id: '3',
      name: 'Leather Handbag',
      imageUrl: 'assets/images/main_image.jpg',
      price: 89.99,
      rating: 4.8,
      status: 'normal',
      category: 'Accessories',
      amount: 15,
    ),
    Product(
      id: '4',
      name: 'Wireless Earbuds',
      imageUrl: 'assets/images/main_image.jpg',
      price: 79.99,
      rating: 4.6,
      status: 'trend',
      category: 'Electronics',
      amount: 33,
    ),
    Product(
      id: '5',
      name: 'Yoga Pants',
      imageUrl: 'assets/images/main_image.jpg',
      price: 34.99,
      rating: 4.3,
      status: 'out_of_stock',
      category: 'Women',
      amount: 0,
    ),
    Product(
      id: '6',
      name: 'Running Shoes',
      imageUrl: 'assets/images/main_image.jpg',
      price: 119.99,
      rating: 4.7,
      status: 'sale',
      category: 'Men',
      amount: 18,
    ),
    Product(
      id: '7',
      name: 'Smart Watch',
      imageUrl: 'assets/images/main_image.jpg',
      price: 199.99,
      rating: 4.4,
      status: 'normal',
      category: 'Accessories',
      amount: 12,
    ),
    Product(
      id: '8',
      name: 'Indoor Plant Pot',
      imageUrl: 'assets/images/main_image.jpg',
      price: 24.99,
      rating: 4.1,
      status: 'trend',
      category: 'Home & Garden',
      amount: 55,
    ),
    Product(
      id: '9',
      name: 'Stylish Blazer',
      imageUrl: 'assets/images/main_image.jpg',
      price: 79.99,
      rating: 4.5,
      status: 'normal',
      category: 'Women',
      amount: 21,
    ),
    Product(
      id: '10',
      name: 'Comfortable Jeans',
      imageUrl: 'assets/images/main_image.jpg',
      price: 59.99,
      rating: 4.3,
      status: 'sale',
      category: 'Men',
      amount: 38,
    ),
    Product(
      id: '11',
      name: 'Designer Sunglasses',
      imageUrl: 'assets/images/main_image.jpg',
      price: 129.99,
      rating: 4.9,
      status: 'trend',
      category: 'Accessories',
      amount: 8,
    ),
    Product(
      id: '12',
      name: 'Bluetooth Speaker',
      imageUrl: 'assets/images/main_image.jpg',
      price: 59.99,
      rating: 4.0,
      status: 'normal',
      category: 'Electronics',
      amount: 27,
    ),
    Product(
      id: '13',
      name: 'Gardening Gloves',
      imageUrl: 'assets/images/main_image.jpg',
      price: 15.99,
      rating: 3.8,
      status: 'normal',
      category: 'Home & Garden',
      amount: 44,
    ),
    Product(
      id: '14',
      name: 'Winter Coat',
      imageUrl: 'assets/images/main_image.jpg',
      price: 149.99,
      rating: 4.7,
      status: 'sale',
      category: 'Women',
      amount: 16,
    ),
    Product(
      id: '15',
      name: 'Dress Shirt',
      imageUrl: 'assets/images/main_image.jpg',
      price: 45.99,
      rating: 4.1,
      status: 'normal',
      category: 'Men',
      amount: 31,
    ),
  ];
}
