import 'package:dashboard/features/Product/Manage%20Existing%20Product/All%20Product/Model/all_product.dart';

class SampleProducts {
  static const List<String> categories = [
    'All Products',
    'Women',
    'Men',
    'Accessories',
    'Electronics',
    'Home & Garden',
  ];

  static final List<Product> products = [
    Product(
      id: '1',
      name: 'Summer Dress',
      category: 'Women',
      department: 'Women',
      gender: 'Female',
      price: 49.99,
      description: 'Beautiful summer dress perfect for warm weather',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Blue',
      favoriteCount: 125,
      salesCount: 89,
      viewCount: 1250,
      averageRating: 4.5,
      reviewCount: 23,
    ),
    Product(
      id: '2',
      name: 'Casual Shirt',
      category: 'Men',
      department: 'Men',
      gender: 'Male',
      price: 29.99,
      description: 'Comfortable casual shirt for everyday wear',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'White',
      favoriteCount: 78,
      salesCount: 156,
      viewCount: 890,
      averageRating: 4.2,
      reviewCount: 34,
    ),
    Product(
      id: '3',
      name: 'Leather Handbag',
      category: 'Accessories',
      department: 'Women',
      gender: 'Female',
      price: 89.99,
      description: 'Premium leather handbag with elegant design',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Brown',
      favoriteCount: 203,
      salesCount: 67,
      viewCount: 2100,
      averageRating: 4.8,
      reviewCount: 45,
    ),
    Product(
      id: '4',
      name: 'Wireless Earbuds',
      category: 'Electronics',
      department: 'Electronics',
      gender: 'Unisex',
      price: 79.99,
      description: 'High-quality wireless earbuds with noise cancellation',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Black',
      favoriteCount: 445,
      salesCount: 234,
      viewCount: 3200,
      averageRating: 4.6,
      reviewCount: 78,
    ),
    Product(
      id: '5',
      name: 'Yoga Pants',
      category: 'Women',
      department: 'Women',
      gender: 'Female',
      price: 34.99,
      description: 'Comfortable yoga pants for workout and casual wear',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Black',
      favoriteCount: 189,
      salesCount: 145,
      viewCount: 1800,
      averageRating: 4.3,
      reviewCount: 67,
    ),
    Product(
      id: '6',
      name: 'Running Shoes',
      category: 'Men',
      department: 'Men',
      gender: 'Male',
      price: 119.99,
      discountPrice: 89.99,
      description: 'Professional running shoes with advanced cushioning',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Gray',
      favoriteCount: 312,
      salesCount: 201,
      viewCount: 2800,
      averageRating: 4.7,
      reviewCount: 89,
    ),
    Product(
      id: '7',
      name: 'Smart Watch',
      category: 'Accessories',
      department: 'Electronics',
      gender: 'Unisex',
      price: 199.99,
      description: 'Advanced smartwatch with health monitoring features',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Silver',
      favoriteCount: 567,
      salesCount: 178,
      viewCount: 4500,
      averageRating: 4.4,
      reviewCount: 123,
    ),
    Product(
      id: '8',
      name: 'Indoor Plant Pot',
      category: 'Home & Garden',
      department: 'Home',
      gender: 'Unisex',
      price: 24.99,
      description: 'Decorative plant pot perfect for indoor plants',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Terracotta',
      favoriteCount: 94,
      salesCount: 87,
      viewCount: 650,
      averageRating: 4.1,
      reviewCount: 28,
    ),
    Product(
      id: '9',
      name: 'Stylish Blazer',
      category: 'Women',
      department: 'Women',
      gender: 'Female',
      price: 79.99,
      description: 'Professional blazer for office and formal occasions',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Navy',
      favoriteCount: 156,
      salesCount: 93,
      viewCount: 1200,
      averageRating: 4.5,
      reviewCount: 41,
    ),
    Product(
      id: '10',
      name: 'Comfortable Jeans',
      category: 'Men',
      department: 'Men',
      gender: 'Male',
      price: 59.99,
      discountPrice: 45.99,
      description: 'Comfortable denim jeans with perfect fit',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Blue',
      favoriteCount: 234,
      salesCount: 167,
      viewCount: 1900,
      averageRating: 4.3,
      reviewCount: 56,
    ),
    Product(
      id: '11',
      name: 'Designer Sunglasses',
      category: 'Accessories',
      department: 'Accessories',
      gender: 'Unisex',
      price: 129.99,
      description: 'Premium designer sunglasses with UV protection',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Black',
      favoriteCount: 378,
      salesCount: 134,
      viewCount: 2500,
      averageRating: 4.9,
      reviewCount: 67,
    ),
    Product(
      id: '12',
      name: 'Bluetooth Speaker',
      category: 'Electronics',
      department: 'Electronics',
      gender: 'Unisex',
      price: 59.99,
      description: 'Portable bluetooth speaker with excellent sound quality',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Red',
      favoriteCount: 289,
      salesCount: 198,
      viewCount: 2200,
      averageRating: 4.0,
      reviewCount: 78,
    ),
    Product(
      id: '13',
      name: 'Gardening Gloves',
      category: 'Home & Garden',
      department: 'Home',
      gender: 'Unisex',
      price: 15.99,
      description: 'Protective gardening gloves for all garden work',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Green',
      favoriteCount: 67,
      salesCount: 112,
      viewCount: 420,
      averageRating: 3.8,
      reviewCount: 34,
    ),
    Product(
      id: '14',
      name: 'Winter Coat',
      category: 'Women',
      department: 'Women',
      gender: 'Female',
      price: 149.99,
      discountPrice: 119.99,
      description: 'Warm winter coat with water-resistant material',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'Black',
      favoriteCount: 445,
      salesCount: 89,
      viewCount: 3100,
      averageRating: 4.7,
      reviewCount: 92,
    ),
    Product(
      id: '15',
      name: 'Dress Shirt',
      category: 'Men',
      department: 'Men',
      gender: 'Male',
      price: 45.99,
      description: 'Formal dress shirt perfect for business occasions',
      imageUrls: ['assets/images/main_image.jpg'],
      color: 'White',
      favoriteCount: 123,
      salesCount: 145,
      viewCount: 980,
      averageRating: 4.1,
      reviewCount: 48,
    ),
  ];

  static String getProductStatus(Product product) {
    if (product.salesCount > 150) return 'trend';
    if (product.discountPrice != null) return 'sale';
    if (product.salesCount == 0) return 'out_of_stock';
    return 'normal';
  }

  static int getProductAmount(Product product) {
    if (product.salesCount == 0) return 0;
    return (100 - product.salesCount).clamp(0, 100);
  }
}
